### ISSUE TITLE
Make certificate scripts configurable

### ISSUE THREAD

**Issue by kipparker** [icebreakerone/perseus-demo-energy#36]
We have hardcoded values for the self-signed certificate scripts used for setting up the local dev environment. Other users may want to enter their own values for the data provider or the client. 

eg.

https://github.com/icebreakerone/perseus-demo-energy/blob/3a3b30a9393a8155c9ec6f29b99886db437acd16/scripts/certmaker.sh#L5

**Comment by padajo** [comment]
A suggestion here would be to change `ca-key.pem` and `ca-cert.pm` to more descriptive names e.g. `perseus-demo-key.pem` because you don't want to overwrite files that may already exist accidentally.

**Comment by padajo** [comment]
A link to a good document on CSRs would be useful too. There's no need to explain something for which documentation already exists. That subject CN is relevant to IB1 and so another organisation should be using their own details here.
